build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    system_packages: true

commands:
  - sudo apt-get update
  - sudo apt-get install -y r-base

python:
  install:
    - requirements: docs/requirements.txt
